### ISSUE TITLE
Test and Investigation of Video Learning Project

### ISSUE THREAD

**Issue by KandilKhaled** [ddobric/neocortexapi-videolearning#1]
I have a problem with running the program, it's unable to create "VideoWriter" due to the attached error.
![Codec-Error](https://user-images.githubusercontent.com/93146682/149825404-7ace7775-d8e4-41fa-88af-329d79f4185b.png)

**Comment by javedcoding** [comment]
It is a problem with selecting the codec for encoding and decoding the video file. Here in initiating the VideoWriter a parameter -1 is put to call the codec selection drop down list. But it is not working with the updated Emgu Library. So I fixed it with hard coding currently.  Put a int fourcc of VideoWriter class method fourcc like this: 
            int fourcc = VideoWriter.Fourcc('M','P','4','V');
            using (VideoWriter videoWriter = new($"{videoOutputPath}.mp4", fourcc, (int)frameRate, dimension, isColor))

I am coming up with greater idea to fix this.
