### ISSUE TITLE
Migration of VideoLearning By CodeBrakers: Quiting with error if Q is the input

### ISSUE THREAD

**Issue by javedcoding** [ddobric/neocortexapi-videolearning#12]
Line(356-419)
do
            {
                userInput = "";
                while (userInput == "")
                {
                    userInput = Console.ReadLine().Replace("\"", "");
                }
                if (userInput == "Q")
                {
                    break;
                }
                testNo += 1;
                NFrame inputFrame = new(new Bitmap(userInput), "TEST", "test", 0, frameWidth, frameHeight, colorMode);
                // Computing user input frame with trained layer 
                var lyrOut = layer1.Compute(inputFrame.EncodedBitArray, false) as ComputeCycle;
                var predictedInputValue = cls.GetPredictedInputValues(lyrOut.PredictiveCells.ToArray(), 5);
                foreach (var possibleFrame in predictedInputValue)
                {
                    bool nextPredictedFrameExists = true;
                    List<NFrame> frameSequence = new();
                    frameSequence.Add(inputFrame);
                    string currentFrameKey = possibleFrame.PredictedInput;

                    NFrame currentFrame = null;
                    while (nextPredictedFrameExists && frameSequence.Count < 42)
                    {
                        foreach(var vs in videoData)
                        {
                            currentFrame = vs.GetNFrameFromFrameKey(currentFrameKey);
                            if (currentFrame != null)
                            {
                                frameSequence.Add(currentFrame);
                                break;
                            }
                        }
                        WriteLineColor($"Predicted nextFrame: {currentFrameKey}", ConsoleColor.Green);

                        var computedSDR = layer1.Compute(currentFrame.EncodedBitArray, false) as ComputeCycle;
                        var predictedNext = cls.GetPredictedInputValues(computedSDR.PredictiveCells.ToArray(), 3);

                        // Check for end of Frame sequence
                        if(predictedNext.Count == 0)
                        {
                            nextPredictedFrameExists = false;
                        }
                        else
                        {
                            currentFrameKey = predictedNext[0].PredictedInput;
                        }
                    }
                    string dir = Path.Combine(testOutputFolder,$"Predicted from {Path.GetFileNameWithoutExtension(userInput)}");
                    if (!Directory.Exists(dir))
                    {
                        Directory.CreateDirectory(dir);
                    }
                    NVideo.NFrameListToVideo(
                        frameSequence,
                        Path.Combine(dir,$"testNo_{testNo}_FirstPossibility_{possibleFrame.Similarity}_FirstLabel_{possibleFrame.PredictedInput}"),
                        (int)(videoData[0].nVideoList[0].frameRate),
                        new Size((int)videoData[0].nVideoList[0].frameWidth, (int)videoData[0].nVideoList[0].frameHeight),
                        true);
                }
            }
            while (userInput != "Q");

So the Problem remains as the Q can be read when all doing is done and user input Q can not be read as file path. So it creates an exception error.

**Comment by Noath2302** [comment]
we have discussed about the error
